with source as (
        select * from {{ source('diabetes', 'patient_records') }}
  ),
  renamed as (
      select
        {{ adapter.quote("encounter_id") }},
        {{ adapter.quote("patient_nbr") }} as patient_id,
        {{ adapter.quote("race") }},
        {{ adapter.quote("gender") }},
        {{ adapter.quote("age") }},
        {{ adapter.quote("weight") }},
        {{ adapter.quote("admission_type_id") }},
        {{ adapter.quote("discharge_disposition_id") }},
        {{ adapter.quote("admission_source_id") }},
        {{ adapter.quote("time_in_hospital") }},
        {{ adapter.quote("payer_code") }},
        {{ adapter.quote("medical_specialty") }},
        {{ adapter.quote("num_lab_procedures") }},
        {{ adapter.quote("num_procedures") }},
        {{ adapter.quote("num_medications") }},
        {{ adapter.quote("number_outpatient") }},
        {{ adapter.quote("number_emergency") }},
        {{ adapter.quote("number_inpatient") }},
        {{ adapter.quote("diag_1") }},
        {{ adapter.quote("diag_2") }},
        {{ adapter.quote("diag_3") }},
        {{ adapter.quote("number_diagnoses") }},
        {{ adapter.quote("max_glu_serum") }},
        {{ adapter.quote("A1Cresult") }} as a1c_result,
        {{ adapter.quote("metformin") }},
        {{ adapter.quote("repaglinide") }},
        {{ adapter.quote("nateglinide") }},
        {{ adapter.quote("chlorpropamide") }},
        {{ adapter.quote("glimepiride") }},
        {{ adapter.quote("acetohexamide") }},
        {{ adapter.quote("glipizide") }},
        {{ adapter.quote("glyburide") }},
        {{ adapter.quote("tolbutamide") }},
        {{ adapter.quote("pioglitazone") }},
        {{ adapter.quote("rosiglitazone") }},
        {{ adapter.quote("acarbose") }},
        {{ adapter.quote("miglitol") }},
        {{ adapter.quote("troglitazone") }},
        {{ adapter.quote("tolazamide") }},
        {{ adapter.quote("examide") }},
        {{ adapter.quote("citoglipton") }},
        {{ adapter.quote("insulin") }},
        {{ adapter.quote("glyburide-metformin") }} as  glyburide_metformin,
        {{ adapter.quote("glipizide-metformin") }} as  glipizide_metformin,
        {{ adapter.quote("glimepiride-pioglitazone") }} as  glimepiride_pioglitazone,
        {{ adapter.quote("metformin-rosiglitazone") }} as metformin_rosiglitazone,
        {{ adapter.quote("metformin-pioglitazone") }} as  metformin_pioglitazone,
        {{ adapter.quote("change") }},
        {{ adapter.quote("diabetesMed") }} as diabetes_medication,
        {{ adapter.quote("readmitted") }}

      from source
  )
  select * from renamed
    